print("Example 1: Instagram")
print("Population: All Instagram followers")
print("Sample: 100 randomly selected followers")
print()
print("Example 2: Zomato")
print("Population: All restaurants on Zomato")
print("Sample: 200 randomly selected restaurants")
print()
print("Example 3: Flipkart")
print("Population: All products on Flipkart")
print("Sample: 500 randomly selected products")
import random
users = []
for i in range(1, 1001):
    users.append("user" + str(i))
sample = random.sample(users, 50)
print("Selected users:")
print(sample)
print("Sampling saves time, money and computational resources.")
print("Collecting every Swiggy order would be very large and difficult.")
print("A properly selected sample can represent the overall orders.")
print("The survey has selection bias.")
print("Only users who recently streamed Bollywood songs are included.")
print("Users with other music preferences are excluded.")
print("Therefore, the sample may not represent all Spotify users.")
print("Random Sampling:")
print("Randomly select users from all BookMyShow users.")
print()
print("Stratified Sampling:")
print("Divide users into groups such as age groups.")
print("Randomly select users from each group.")